import { StateGraph, type GraphNode,START,END, StateSchema,type CompiledStateGraph } from "@langchain/langgraph";
import z from "zod"
import { mistralModel,cohereModel, geminiModel } from "./model.ai.js";
import { createAgent, providerStrategy } from "langchain";
import { HumanMessage } from "@langchain/core/messages";



import { searchWeb } from "./tavily.ai.js";

const state = new StateSchema({
    problem: z.string().default(""),
    searchContext: z.string().default(""),
    solution_1: z.string().default(""),
    solution_2: z.string().default(""),
    judgeResult: z.object({
        solution_1_score: z.number().default(0),
        solution_2_score: z.number().default(0),
        solution_1_reasoning: z.string().default(""),
        solution_2_reasoning: z.string().default(""),
    })
})

const searchNode: GraphNode<typeof state> = async (state) => {
    let searchResults = "";
    try {
        searchResults = await searchWeb(state.problem);
    } catch (err: any) {
        console.error("Search node error:", err?.message || err);
    }
    return {
        searchContext: searchResults
    };
};

const solutionNode: GraphNode<typeof state> = async (state) => {
    let sol1Text = "";
    let sol2Text = "";

    const promptWithContext = state.searchContext
        ? `${state.problem}\n\n[Real-Time Internet Information via Tavily Search]:\n${state.searchContext}\n\nPlease utilize the above up-to-date web information if relevant to address the user query.`
        : state.problem;

    try {
        const mistralResponse = await mistralModel.invoke(promptWithContext);
        sol1Text = mistralResponse.text;
    } catch (err: any) {
        console.error("Mistral Model Error:", err?.message || err);
        sol1Text = `⚠️ **Mistral API Notice**: Rate limit reached or model unavailable. (${err?.message || "HTTP 429 Too Many Requests"})`;
    }

    try {
        const cohereResponse = await cohereModel.invoke(promptWithContext);
        sol2Text = cohereResponse.text;
    } catch (err: any) {
        console.error("Cohere Model Error:", err?.message || err);
        sol2Text = `⚠️ **Cohere API Notice**: Rate limit reached or model unavailable. (${err?.message || "HTTP 429 Too Many Requests"})`;
    }

    return {
        solution_1: sol1Text,
        solution_2: sol2Text,
    }
}

const judgeNode: GraphNode<typeof state> = async (state) => {
    const { problem, solution_1, solution_2 } = state;

    try {
        const judge = createAgent({
            model: geminiModel,
            responseFormat: providerStrategy(z.object({
                solution_1_score: z.number().min(0).max(10),
                solution_2_score: z.number().min(0).max(10),
                solution_1_reasoning: z.string(),
                solution_2_reasoning: z.string(),
            })),
            systemPrompt: `You are a judge tasked with evaluating two solutions generated by different AI models. Please provide a score out of 10 for each solution, along with your reasoning for the scores`
        });

        const judgeResponse = await judge.invoke({
            messages: [
                new HumanMessage(`
                    problem: ${problem}
                    solution_1: ${solution_1}
                    solution_2: ${solution_2}
                    Please evaluate the solutions and provide scores and reasoning for each solution.
                `)
            ]
        });

        if (judgeResponse && judgeResponse.structuredResponse) {
            const {
                solution_1_score,
                solution_2_score,
                solution_1_reasoning,
                solution_2_reasoning,
            } = judgeResponse.structuredResponse;

            return {
                judgeResult: {
                    solution_1_score: solution_1_score ?? 5,
                    solution_2_score: solution_2_score ?? 5,
                    solution_1_reasoning: solution_1_reasoning || "Evaluation completed.",
                    solution_2_reasoning: solution_2_reasoning || "Evaluation completed.",
                }
            };
        }
    } catch (err: any) {
        console.error("Gemini Judge Node Error:", err?.message || err);
    }

    return {
        judgeResult: {
            solution_1_score: 5,
            solution_2_score: 5,
            solution_1_reasoning: "Automated Evaluation: One or more AI model providers hit a rate limit or API delay. Please try again shortly.",
            solution_2_reasoning: "Automated Evaluation: One or more AI model providers hit a rate limit or API delay. Please try again shortly.",
        }
    };
}


const graph = new StateGraph(state)
    .addNode("search", searchNode)
    .addNode("solution", solutionNode)
    .addNode("judgeNode", judgeNode)
    .addEdge(START, "search")
    .addEdge("search", "solution")
    .addEdge("solution", "judgeNode")
    .addEdge("judgeNode", END)
    .compile()


export default async function runGraph(problem: string){
    const result = await graph.invoke({
        problem: problem
    })

    console.log(result)
    return result

}