import { StateGraph, type GraphNode,START,END, StateSchema,type CompiledStateGraph } from "@langchain/langgraph";
import z from "zod"
import { mistralModel,cohereModel, geminiModel } from "./model.ai.js";
import { HumanMessage, SystemMessage } from "@langchain/core/messages";



import { searchWeb } from "./tavily.ai.js";

function sleep(ms: number) {
    return new Promise((resolve) => setTimeout(resolve, ms));
}

function isRetryableError(err: any) {
    const msg = String(err?.message || err?.body || err || "").toLowerCase();
    if (
        msg.includes("rate limit") ||
        msg.includes("429") ||
        msg.includes("too many requests") ||
        msg.includes("resource_exhausted") ||
        msg.includes("quota")
    ) return true;
    // provider-specific status fields
    if (
        err?.status === 429 ||
        err?.raw_status_code === 429 ||
        err?.statusCode === 429 ||
        err?.response?.status === 429
    ) return true;
    return false;
}

async function invokeWithRetries(model: any, input: any, attempts = 4, delay = 1500) {
    let lastErr: any;
    let backoff = delay;
    for (let i = 0; i < attempts; i++) {
        try {
            return await model.invoke(input);
        } catch (err: any) {
            lastErr = err;
            if (!isRetryableError(err) || i === attempts - 1) break;
            const jitter = Math.floor(Math.random() * 400);
            const sleepMs = backoff + jitter;
            console.warn(`Model invoke failed (attempt ${i + 1}/${attempts}), retrying in ${sleepMs}ms:`, err?.message || err);
            await sleep(sleepMs);
            backoff *= 2;
        }
    }
    throw lastErr;
}

const state = new StateSchema({
    problem: z.string().default(""),
    searchContext: z.string().default(""),
    solution_1: z.string().default(""),
    solution_2: z.string().default(""),
    judgeResult: z.object({
        solution_1_score: z.number().default(0),
        solution_2_score: z.number().default(0),
        solution_1_reasoning: z.string().default(""),
        solution_2_reasoning: z.string().default(""),
    })
})

const searchNode: GraphNode<typeof state> = async (state) => {
    let searchResults = "";
    try {
        searchResults = await searchWeb(state.problem);
    } catch (err: any) {
        console.error("Search node error:", err?.message || err);
    }
    return {
        searchContext: searchResults
    };
};

const solutionNode: GraphNode<typeof state> = async (state) => {
    let sol1Text = "";
    let sol2Text = "";

    // Clean non-breaking spaces (\xa0) and control characters from web snippets
    const cleanSearchContext = (state.searchContext || "")
        .replace(/\u00a0/g, " ")
        .replace(/[\u0002-\u0008]/g, "")
        .trim();

    const promptWithContext = cleanSearchContext
        ? `${state.problem}\n\n[Real-Time Internet Information via Tavily Search]:\n${cleanSearchContext}\n\nPlease utilize the above up-to-date web information if relevant to address the user query.`
        : state.problem;

    try {
        const mistralResponse = await invokeWithRetries(mistralModel, promptWithContext, 4, 1500);
        sol1Text = mistralResponse?.text || String(mistralResponse || "");
    } catch (err: any) {
        console.error("Mistral Model Error:", err?.message || err);
        sol1Text = `⚠️ **Mistral API Notice**: Rate limit or model error. (${err?.message || "HTTP 429 Too Many Requests"})\n\n*Please wait a few seconds before trying again.*`;
    }

    try {
        const cohereResponse = await invokeWithRetries(cohereModel, promptWithContext, 4, 1500);
        sol2Text = cohereResponse?.text || String(cohereResponse || "");
    } catch (err: any) {
        console.error("Cohere Model Error:", err?.message || err);
        sol2Text = `⚠️ **Cohere API Notice**: Rate limit or model error. (${err?.message || "HTTP 429 Too Many Requests"})\n\n*Please wait a few seconds before trying again.*`;
    }

    return {
        solution_1: sol1Text,
        solution_2: sol2Text,
    }
}

const judgeSchema = z.object({
    solution_1_score: z.number().min(0).max(10),
    solution_2_score: z.number().min(0).max(10),
    solution_1_reasoning: z.string(),
    solution_2_reasoning: z.string(),
});

const judgeNode: GraphNode<typeof state> = async (state) => {
    const { problem, solution_1, solution_2 } = state;

    try {
        const judgeStructuredModel = geminiModel.withStructuredOutput(judgeSchema);

        const judgeResponse = await invokeWithRetries(
            judgeStructuredModel,
            [
                new SystemMessage("You are an expert AI judge evaluating two candidate solutions generated by AI models for a user query. Provide an objective score out of 10 and concise reasoning for each solution based on accuracy, depth, and clarity."),
                new HumanMessage(`
Problem: ${problem}

Solution 1:
${solution_1}

Solution 2:
${solution_2}

Please evaluate both solutions and output the scores and reasoning.
                `)
            ],
            4,
            1500
        );

        if (judgeResponse) {
            return {
                judgeResult: {
                    solution_1_score: Number(judgeResponse.solution_1_score) || 5,
                    solution_2_score: Number(judgeResponse.solution_2_score) || 5,
                    solution_1_reasoning: judgeResponse.solution_1_reasoning || "Evaluation completed.",
                    solution_2_reasoning: judgeResponse.solution_2_reasoning || "Evaluation completed.",
                }
            };
        }
    } catch (err: any) {
        console.error("Gemini Judge Node Error:", err?.message || err);
    }

    return {
        judgeResult: {
            solution_1_score: 5,
            solution_2_score: 5,
            solution_1_reasoning: "Automated Evaluation: One or more AI model providers hit a rate limit or API delay. Please try again shortly.",
            solution_2_reasoning: "Automated Evaluation: One or more AI model providers hit a rate limit or API delay. Please try again shortly.",
        }
    };
}


const graph = new StateGraph(state)
    .addNode("search", searchNode)
    .addNode("solution", solutionNode)
    .addNode("judgeNode", judgeNode)
    .addEdge(START, "search")
    .addEdge("search", "solution")
    .addEdge("solution", "judgeNode")
    .addEdge("judgeNode", END)
    .compile()


export default async function runGraph(problem: string){
    const result = await graph.invoke({
        problem: problem
    })

    console.log(result)
    return result

}